// File generated from our OpenAPI spec by Stainless.

package com.dedalus_sdk.api.models

import com.dedalus_sdk.api.core.JsonValue
import com.dedalus_sdk.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ModelSettingsTest {

    @Test
    fun create() {
        val modelSettings =
            ModelSettings.builder()
                .attributes(
                    ModelSettings.Attributes.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .audio(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .deferred(true)
                .extraArgs(
                    ModelSettings.ExtraArgs.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .extraHeaders(
                    ModelSettings.ExtraHeaders.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .extraQuery(
                    ModelSettings.ExtraQuery.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .frequencyPenalty(0.0)
                .generationConfig(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .includeUsage(true)
                .inputAudioFormat("input_audio_format")
                .inputAudioTranscription(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .logitBias(
                    ModelSettings.LogitBias.builder()
                        .putAdditionalProperty("foo", JsonValue.from(0))
                        .build()
                )
                .logprobs(true)
                .maxCompletionTokens(0L)
                .maxTokens(0L)
                .metadata(
                    ModelSettings.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .addModality("string")
                .n(0L)
                .outputAudioFormat("output_audio_format")
                .parallelToolCalls(true)
                .prediction(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .presencePenalty(0.0)
                .promptCacheKey("prompt_cache_key")
                .reasoning(
                    Reasoning.builder()
                        .effort(Reasoning.Effort.NONE)
                        .generateSummary(Reasoning.GenerateSummary.AUTO)
                        .summary(Reasoning.Summary.AUTO)
                        .build()
                )
                .reasoningEffort("reasoning_effort")
                .responseFormat(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .safetyIdentifier("safety_identifier")
                .addSafetySetting(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .searchParameters(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .seed(0L)
                .serviceTier("service_tier")
                .stop("string")
                .store(true)
                .stream(true)
                .streamOptions(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .structuredOutput(JsonValue.from(mapOf<String, Any>()))
                .systemInstruction(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .temperature(0.0)
                .thinking(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .timeout(0.0)
                .toolChoice(ToolChoice.UnionMember0.AUTO)
                .toolConfig(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .topK(0L)
                .topLogprobs(0L)
                .topP(0.0)
                .truncation(ModelSettings.Truncation.AUTO)
                .turnDetection(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .user("user")
                .verbosity("verbosity")
                .voice("voice")
                .webSearchOptions(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .build()

        assertThat(modelSettings.attributes())
            .isEqualTo(
                ModelSettings.Attributes.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(modelSettings.audio())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.deferred()).isEqualTo(true)
        assertThat(modelSettings.extraArgs())
            .isEqualTo(
                ModelSettings.ExtraArgs.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(modelSettings.extraHeaders())
            .isEqualTo(
                ModelSettings.ExtraHeaders.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.extraQuery())
            .isEqualTo(
                ModelSettings.ExtraQuery.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(modelSettings.frequencyPenalty()).isEqualTo(0.0)
        assertThat(modelSettings.generationConfig())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.includeUsage()).isEqualTo(true)
        assertThat(modelSettings.inputAudioFormat()).isEqualTo("input_audio_format")
        assertThat(modelSettings.inputAudioTranscription())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.logitBias())
            .isEqualTo(
                ModelSettings.LogitBias.builder()
                    .putAdditionalProperty("foo", JsonValue.from(0))
                    .build()
            )
        assertThat(modelSettings.logprobs()).isEqualTo(true)
        assertThat(modelSettings.maxCompletionTokens()).isEqualTo(0L)
        assertThat(modelSettings.maxTokens()).isEqualTo(0L)
        assertThat(modelSettings.metadata())
            .isEqualTo(
                ModelSettings.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.modalities()).containsExactly("string")
        assertThat(modelSettings.n()).isEqualTo(0L)
        assertThat(modelSettings.outputAudioFormat()).isEqualTo("output_audio_format")
        assertThat(modelSettings.parallelToolCalls()).isEqualTo(true)
        assertThat(modelSettings.prediction())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.presencePenalty()).isEqualTo(0.0)
        assertThat(modelSettings.promptCacheKey()).isEqualTo("prompt_cache_key")
        assertThat(modelSettings.reasoning())
            .isEqualTo(
                Reasoning.builder()
                    .effort(Reasoning.Effort.NONE)
                    .generateSummary(Reasoning.GenerateSummary.AUTO)
                    .summary(Reasoning.Summary.AUTO)
                    .build()
            )
        assertThat(modelSettings.reasoningEffort()).isEqualTo("reasoning_effort")
        assertThat(modelSettings.responseFormat())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.safetyIdentifier()).isEqualTo("safety_identifier")
        assertThat(modelSettings.safetySettings())
            .containsExactly(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.searchParameters())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.seed()).isEqualTo(0L)
        assertThat(modelSettings.serviceTier()).isEqualTo("service_tier")
        assertThat(modelSettings.stop()).isEqualTo(ModelSettings.Stop.ofString("string"))
        assertThat(modelSettings.store()).isEqualTo(true)
        assertThat(modelSettings.stream()).isEqualTo(true)
        assertThat(modelSettings.streamOptions())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings._structuredOutput())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(modelSettings.systemInstruction())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.temperature()).isEqualTo(0.0)
        assertThat(modelSettings.thinking())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.timeout()).isEqualTo(0.0)
        assertThat(modelSettings.toolChoice())
            .isEqualTo(ToolChoice.ofUnionMember0(ToolChoice.UnionMember0.AUTO))
        assertThat(modelSettings.toolConfig())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.topK()).isEqualTo(0L)
        assertThat(modelSettings.topLogprobs()).isEqualTo(0L)
        assertThat(modelSettings.topP()).isEqualTo(0.0)
        assertThat(modelSettings.truncation()).isEqualTo(ModelSettings.Truncation.AUTO)
        assertThat(modelSettings.turnDetection())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(modelSettings.user()).isEqualTo("user")
        assertThat(modelSettings.verbosity()).isEqualTo("verbosity")
        assertThat(modelSettings.voice()).isEqualTo("voice")
        assertThat(modelSettings.webSearchOptions())
            .isEqualTo(
                JsonObjectInput.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val modelSettings =
            ModelSettings.builder()
                .attributes(
                    ModelSettings.Attributes.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .audio(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .deferred(true)
                .extraArgs(
                    ModelSettings.ExtraArgs.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .extraHeaders(
                    ModelSettings.ExtraHeaders.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .extraQuery(
                    ModelSettings.ExtraQuery.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .frequencyPenalty(0.0)
                .generationConfig(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .includeUsage(true)
                .inputAudioFormat("input_audio_format")
                .inputAudioTranscription(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .logitBias(
                    ModelSettings.LogitBias.builder()
                        .putAdditionalProperty("foo", JsonValue.from(0))
                        .build()
                )
                .logprobs(true)
                .maxCompletionTokens(0L)
                .maxTokens(0L)
                .metadata(
                    ModelSettings.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .addModality("string")
                .n(0L)
                .outputAudioFormat("output_audio_format")
                .parallelToolCalls(true)
                .prediction(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .presencePenalty(0.0)
                .promptCacheKey("prompt_cache_key")
                .reasoning(
                    Reasoning.builder()
                        .effort(Reasoning.Effort.NONE)
                        .generateSummary(Reasoning.GenerateSummary.AUTO)
                        .summary(Reasoning.Summary.AUTO)
                        .build()
                )
                .reasoningEffort("reasoning_effort")
                .responseFormat(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .safetyIdentifier("safety_identifier")
                .addSafetySetting(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .searchParameters(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .seed(0L)
                .serviceTier("service_tier")
                .stop("string")
                .store(true)
                .stream(true)
                .streamOptions(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .structuredOutput(JsonValue.from(mapOf<String, Any>()))
                .systemInstruction(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .temperature(0.0)
                .thinking(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .timeout(0.0)
                .toolChoice(ToolChoice.UnionMember0.AUTO)
                .toolConfig(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .topK(0L)
                .topLogprobs(0L)
                .topP(0.0)
                .truncation(ModelSettings.Truncation.AUTO)
                .turnDetection(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .user("user")
                .verbosity("verbosity")
                .voice("voice")
                .webSearchOptions(
                    JsonObjectInput.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .build()

        val roundtrippedModelSettings =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(modelSettings),
                jacksonTypeRef<ModelSettings>(),
            )

        assertThat(roundtrippedModelSettings).isEqualTo(modelSettings)
    }
}
