// File generated from our OpenAPI spec by Stainless.

package com.dedalus_sdk.api.models.chat.completions

import com.dedalus_sdk.api.core.BaseDeserializer
import com.dedalus_sdk.api.core.BaseSerializer
import com.dedalus_sdk.api.core.ExcludeMissing
import com.dedalus_sdk.api.core.JsonField
import com.dedalus_sdk.api.core.JsonMissing
import com.dedalus_sdk.api.core.JsonValue
import com.dedalus_sdk.api.core.allMaxBy
import com.dedalus_sdk.api.core.checkKnown
import com.dedalus_sdk.api.core.checkRequired
import com.dedalus_sdk.api.core.getOrThrow
import com.dedalus_sdk.api.core.toImmutable
import com.dedalus_sdk.api.errors.DedalusInvalidDataException
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.ObjectCodec
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.annotation.JsonDeserialize
import com.fasterxml.jackson.databind.annotation.JsonSerialize
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.util.Collections
import java.util.Objects

/**
 * Messages sent by the model in response to user messages.
 *
 * Fields:
 * - content (optional): str | Annotated[list[ChatCompletionRequestAssistantMessageContentPart],
 *   MinLen(1), ArrayTitle("ChatCompletionRequestAssistantMessageContentArray")] | None
 * - refusal (optional): str | None
 * - role (required): Literal["assistant"]
 * - name (optional): str
 * - audio (optional): Audio | None
 * - tool_calls (optional): ChatCompletionMessageToolCalls
 * - function_call (optional): FunctionCall | None
 */
class ChatCompletionAssistantMessageParam
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val role: JsonValue,
    private val audio: JsonField<Audio>,
    private val content: JsonField<Content>,
    private val functionCall: JsonField<FunctionCall>,
    private val name: JsonField<String>,
    private val refusal: JsonField<String>,
    private val toolCalls: JsonField<List<ToolCall>>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("role") @ExcludeMissing role: JsonValue = JsonMissing.of(),
        @JsonProperty("audio") @ExcludeMissing audio: JsonField<Audio> = JsonMissing.of(),
        @JsonProperty("content") @ExcludeMissing content: JsonField<Content> = JsonMissing.of(),
        @JsonProperty("function_call")
        @ExcludeMissing
        functionCall: JsonField<FunctionCall> = JsonMissing.of(),
        @JsonProperty("name") @ExcludeMissing name: JsonField<String> = JsonMissing.of(),
        @JsonProperty("refusal") @ExcludeMissing refusal: JsonField<String> = JsonMissing.of(),
        @JsonProperty("tool_calls")
        @ExcludeMissing
        toolCalls: JsonField<List<ToolCall>> = JsonMissing.of(),
    ) : this(role, audio, content, functionCall, name, refusal, toolCalls, mutableMapOf())

    /**
     * The role of the messages author, in this case `assistant`.
     *
     * Expected to always return the following:
     * ```kotlin
     * JsonValue.from("assistant")
     * ```
     *
     * However, this method can be useful for debugging and logging (e.g. if the server responded
     * with an unexpected value).
     */
    @JsonProperty("role") @ExcludeMissing fun _role(): JsonValue = role

    /**
     * Data about a previous audio response from the model. [Learn more](/docs/guides/audio).
     *
     * Fields:
     * - id (required): str
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun audio(): Audio? = audio.getNullable("audio")

    /**
     * The contents of the assistant message. Required unless `tool_calls` or `function_call` is
     * specified.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun content(): Content? = content.getNullable("content")

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be
     * called, as generated by the model.
     *
     * Fields:
     * - arguments (required): str
     * - name (required): str
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun functionCall(): FunctionCall? = functionCall.getNullable("function_call")

    /**
     * An optional name for the participant. Provides the model information to differentiate between
     * participants of the same role.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun name(): String? = name.getNullable("name")

    /**
     * The refusal message by the assistant.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun refusal(): String? = refusal.getNullable("refusal")

    /**
     * The tool calls generated by the model, such as function calls.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun toolCalls(): List<ToolCall>? = toolCalls.getNullable("tool_calls")

    /**
     * Returns the raw JSON value of [audio].
     *
     * Unlike [audio], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("audio") @ExcludeMissing fun _audio(): JsonField<Audio> = audio

    /**
     * Returns the raw JSON value of [content].
     *
     * Unlike [content], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("content") @ExcludeMissing fun _content(): JsonField<Content> = content

    /**
     * Returns the raw JSON value of [functionCall].
     *
     * Unlike [functionCall], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("function_call")
    @ExcludeMissing
    fun _functionCall(): JsonField<FunctionCall> = functionCall

    /**
     * Returns the raw JSON value of [name].
     *
     * Unlike [name], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("name") @ExcludeMissing fun _name(): JsonField<String> = name

    /**
     * Returns the raw JSON value of [refusal].
     *
     * Unlike [refusal], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("refusal") @ExcludeMissing fun _refusal(): JsonField<String> = refusal

    /**
     * Returns the raw JSON value of [toolCalls].
     *
     * Unlike [toolCalls], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("tool_calls")
    @ExcludeMissing
    fun _toolCalls(): JsonField<List<ToolCall>> = toolCalls

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of
         * [ChatCompletionAssistantMessageParam].
         */
        fun builder() = Builder()
    }

    /** A builder for [ChatCompletionAssistantMessageParam]. */
    class Builder internal constructor() {

        private var role: JsonValue = JsonValue.from("assistant")
        private var audio: JsonField<Audio> = JsonMissing.of()
        private var content: JsonField<Content> = JsonMissing.of()
        private var functionCall: JsonField<FunctionCall> = JsonMissing.of()
        private var name: JsonField<String> = JsonMissing.of()
        private var refusal: JsonField<String> = JsonMissing.of()
        private var toolCalls: JsonField<MutableList<ToolCall>>? = null
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        internal fun from(
            chatCompletionAssistantMessageParam: ChatCompletionAssistantMessageParam
        ) = apply {
            role = chatCompletionAssistantMessageParam.role
            audio = chatCompletionAssistantMessageParam.audio
            content = chatCompletionAssistantMessageParam.content
            functionCall = chatCompletionAssistantMessageParam.functionCall
            name = chatCompletionAssistantMessageParam.name
            refusal = chatCompletionAssistantMessageParam.refusal
            toolCalls = chatCompletionAssistantMessageParam.toolCalls.map { it.toMutableList() }
            additionalProperties =
                chatCompletionAssistantMessageParam.additionalProperties.toMutableMap()
        }

        /**
         * Sets the field to an arbitrary JSON value.
         *
         * It is usually unnecessary to call this method because the field defaults to the
         * following:
         * ```kotlin
         * JsonValue.from("assistant")
         * ```
         *
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun role(role: JsonValue) = apply { this.role = role }

        /**
         * Data about a previous audio response from the model. [Learn more](/docs/guides/audio).
         *
         * Fields:
         * - id (required): str
         */
        fun audio(audio: Audio?) = audio(JsonField.ofNullable(audio))

        /**
         * Sets [Builder.audio] to an arbitrary JSON value.
         *
         * You should usually call [Builder.audio] with a well-typed [Audio] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun audio(audio: JsonField<Audio>) = apply { this.audio = audio }

        /**
         * The contents of the assistant message. Required unless `tool_calls` or `function_call` is
         * specified.
         */
        fun content(content: Content?) = content(JsonField.ofNullable(content))

        /**
         * Sets [Builder.content] to an arbitrary JSON value.
         *
         * You should usually call [Builder.content] with a well-typed [Content] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun content(content: JsonField<Content>) = apply { this.content = content }

        /** Alias for calling [content] with `Content.ofString(string)`. */
        fun content(string: String) = content(Content.ofString(string))

        /**
         * Alias for calling [content] with
         * `Content.ofChatCompletionRequestAssistantMessageContentArray(chatCompletionRequestAssistantMessageContentArray)`.
         */
        fun contentOfChatCompletionRequestAssistantMessageContentArray(
            chatCompletionRequestAssistantMessageContentArray:
                List<Content.UnnamedSchemaWithArrayParent1>
        ) =
            content(
                Content.ofChatCompletionRequestAssistantMessageContentArray(
                    chatCompletionRequestAssistantMessageContentArray
                )
            )

        /**
         * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should
         * be called, as generated by the model.
         *
         * Fields:
         * - arguments (required): str
         * - name (required): str
         */
        fun functionCall(functionCall: FunctionCall?) =
            functionCall(JsonField.ofNullable(functionCall))

        /**
         * Sets [Builder.functionCall] to an arbitrary JSON value.
         *
         * You should usually call [Builder.functionCall] with a well-typed [FunctionCall] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun functionCall(functionCall: JsonField<FunctionCall>) = apply {
            this.functionCall = functionCall
        }

        /**
         * An optional name for the participant. Provides the model information to differentiate
         * between participants of the same role.
         */
        fun name(name: String) = name(JsonField.of(name))

        /**
         * Sets [Builder.name] to an arbitrary JSON value.
         *
         * You should usually call [Builder.name] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun name(name: JsonField<String>) = apply { this.name = name }

        /** The refusal message by the assistant. */
        fun refusal(refusal: String?) = refusal(JsonField.ofNullable(refusal))

        /**
         * Sets [Builder.refusal] to an arbitrary JSON value.
         *
         * You should usually call [Builder.refusal] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun refusal(refusal: JsonField<String>) = apply { this.refusal = refusal }

        /** The tool calls generated by the model, such as function calls. */
        fun toolCalls(toolCalls: List<ToolCall>) = toolCalls(JsonField.of(toolCalls))

        /**
         * Sets [Builder.toolCalls] to an arbitrary JSON value.
         *
         * You should usually call [Builder.toolCalls] with a well-typed `List<ToolCall>` value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun toolCalls(toolCalls: JsonField<List<ToolCall>>) = apply {
            this.toolCalls = toolCalls.map { it.toMutableList() }
        }

        /**
         * Adds a single [ToolCall] to [toolCalls].
         *
         * @throws IllegalStateException if the field was previously set to a non-list.
         */
        fun addToolCall(toolCall: ToolCall) = apply {
            toolCalls =
                (toolCalls ?: JsonField.of(mutableListOf())).also {
                    checkKnown("toolCalls", it).add(toolCall)
                }
        }

        /** Alias for calling [addToolCall] with `ToolCall.ofFunction(function)`. */
        fun addToolCall(function: ChatCompletionMessageToolCall) =
            addToolCall(ToolCall.ofFunction(function))

        /** Alias for calling [addToolCall] with `ToolCall.ofCustom(custom)`. */
        fun addToolCall(custom: ChatCompletionMessageCustomToolCall) =
            addToolCall(ToolCall.ofCustom(custom))

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [ChatCompletionAssistantMessageParam].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         */
        fun build(): ChatCompletionAssistantMessageParam =
            ChatCompletionAssistantMessageParam(
                role,
                audio,
                content,
                functionCall,
                name,
                refusal,
                (toolCalls ?: JsonMissing.of()).map { it.toImmutable() },
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws DedalusInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): ChatCompletionAssistantMessageParam = apply {
        if (validated) {
            return@apply
        }

        _role().let {
            if (it != JsonValue.from("assistant")) {
                throw DedalusInvalidDataException("'role' is invalid, received $it")
            }
        }
        audio()?.validate()
        content()?.validate()
        functionCall()?.validate()
        name()
        refusal()
        toolCalls()?.forEach { it.validate() }
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: DedalusInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    internal fun validity(): Int =
        role.let { if (it == JsonValue.from("assistant")) 1 else 0 } +
            (audio.asKnown()?.validity() ?: 0) +
            (content.asKnown()?.validity() ?: 0) +
            (functionCall.asKnown()?.validity() ?: 0) +
            (if (name.asKnown() == null) 0 else 1) +
            (if (refusal.asKnown() == null) 0 else 1) +
            (toolCalls.asKnown()?.sumOf { it.validity().toInt() } ?: 0)

    /**
     * The contents of the assistant message. Required unless `tool_calls` or `function_call` is
     * specified.
     */
    @JsonDeserialize(using = Content.Deserializer::class)
    @JsonSerialize(using = Content.Serializer::class)
    class Content
    private constructor(
        private val string: String? = null,
        private val chatCompletionRequestAssistantMessageContentArray:
            List<UnnamedSchemaWithArrayParent1>? =
            null,
        private val _json: JsonValue? = null,
    ) {

        fun string(): String? = string

        fun chatCompletionRequestAssistantMessageContentArray():
            List<UnnamedSchemaWithArrayParent1>? = chatCompletionRequestAssistantMessageContentArray

        fun isString(): Boolean = string != null

        fun isChatCompletionRequestAssistantMessageContentArray(): Boolean =
            chatCompletionRequestAssistantMessageContentArray != null

        fun asString(): String = string.getOrThrow("string")

        fun asChatCompletionRequestAssistantMessageContentArray():
            List<UnnamedSchemaWithArrayParent1> =
            chatCompletionRequestAssistantMessageContentArray.getOrThrow(
                "chatCompletionRequestAssistantMessageContentArray"
            )

        fun _json(): JsonValue? = _json

        /**
         * Maps this instance's current variant to a value of type [T] using the given [visitor].
         *
         * Note that this method is _not_ forwards compatible with new variants from the API, unless
         * [visitor] overrides [Visitor.unknown]. To handle variants not known to this version of
         * the SDK gracefully, consider overriding [Visitor.unknown]:
         * ```kotlin
         * import com.dedalus_sdk.api.core.JsonValue
         *
         * val result: String? = content.accept(object : Content.Visitor<String?> {
         *     override fun visitString(string: String): String? = string.toString()
         *
         *     // ...
         *
         *     override fun unknown(json: JsonValue?): String? {
         *         // Or inspect the `json`.
         *         return null
         *     }
         * })
         * ```
         *
         * @throws DedalusInvalidDataException if [Visitor.unknown] is not overridden in [visitor]
         *   and the current variant is unknown.
         */
        fun <T> accept(visitor: Visitor<T>): T =
            when {
                string != null -> visitor.visitString(string)
                chatCompletionRequestAssistantMessageContentArray != null ->
                    visitor.visitChatCompletionRequestAssistantMessageContentArray(
                        chatCompletionRequestAssistantMessageContentArray
                    )
                else -> visitor.unknown(_json)
            }

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws DedalusInvalidDataException if any value type in this object doesn't match its
         *   expected type.
         */
        fun validate(): Content = apply {
            if (validated) {
                return@apply
            }

            accept(
                object : Visitor<Unit> {
                    override fun visitString(string: String) {}

                    override fun visitChatCompletionRequestAssistantMessageContentArray(
                        chatCompletionRequestAssistantMessageContentArray:
                            List<UnnamedSchemaWithArrayParent1>
                    ) {
                        chatCompletionRequestAssistantMessageContentArray.forEach { it.validate() }
                    }
                }
            )
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: DedalusInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        internal fun validity(): Int =
            accept(
                object : Visitor<Int> {
                    override fun visitString(string: String) = 1

                    override fun visitChatCompletionRequestAssistantMessageContentArray(
                        chatCompletionRequestAssistantMessageContentArray:
                            List<UnnamedSchemaWithArrayParent1>
                    ) =
                        chatCompletionRequestAssistantMessageContentArray.sumOf {
                            it.validity().toInt()
                        }

                    override fun unknown(json: JsonValue?) = 0
                }
            )

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is Content &&
                string == other.string &&
                chatCompletionRequestAssistantMessageContentArray ==
                    other.chatCompletionRequestAssistantMessageContentArray
        }

        override fun hashCode(): Int =
            Objects.hash(string, chatCompletionRequestAssistantMessageContentArray)

        override fun toString(): String =
            when {
                string != null -> "Content{string=$string}"
                chatCompletionRequestAssistantMessageContentArray != null ->
                    "Content{chatCompletionRequestAssistantMessageContentArray=$chatCompletionRequestAssistantMessageContentArray}"
                _json != null -> "Content{_unknown=$_json}"
                else -> throw IllegalStateException("Invalid Content")
            }

        companion object {

            fun ofString(string: String) = Content(string = string)

            fun ofChatCompletionRequestAssistantMessageContentArray(
                chatCompletionRequestAssistantMessageContentArray:
                    List<UnnamedSchemaWithArrayParent1>
            ) =
                Content(
                    chatCompletionRequestAssistantMessageContentArray =
                        chatCompletionRequestAssistantMessageContentArray.toImmutable()
                )
        }

        /**
         * An interface that defines how to map each variant of [Content] to a value of type [T].
         */
        interface Visitor<out T> {

            fun visitString(string: String): T

            fun visitChatCompletionRequestAssistantMessageContentArray(
                chatCompletionRequestAssistantMessageContentArray:
                    List<UnnamedSchemaWithArrayParent1>
            ): T

            /**
             * Maps an unknown variant of [Content] to a value of type [T].
             *
             * An instance of [Content] can contain an unknown variant if it was deserialized from
             * data that doesn't match any known variant. For example, if the SDK is on an older
             * version than the API, then the API may respond with new variants that the SDK is
             * unaware of.
             *
             * @throws DedalusInvalidDataException in the default implementation.
             */
            fun unknown(json: JsonValue?): T {
                throw DedalusInvalidDataException("Unknown Content: $json")
            }
        }

        internal class Deserializer : BaseDeserializer<Content>(Content::class) {

            override fun ObjectCodec.deserialize(node: JsonNode): Content {
                val json = JsonValue.fromJsonNode(node)

                val bestMatches =
                    sequenceOf(
                            tryDeserialize(node, jacksonTypeRef<String>())?.let {
                                Content(string = it, _json = json)
                            },
                            tryDeserialize(
                                    node,
                                    jacksonTypeRef<List<UnnamedSchemaWithArrayParent1>>(),
                                )
                                ?.let {
                                    Content(
                                        chatCompletionRequestAssistantMessageContentArray = it,
                                        _json = json,
                                    )
                                },
                        )
                        .filterNotNull()
                        .allMaxBy { it.validity() }
                        .toList()
                return when (bestMatches.size) {
                    // This can happen if what we're deserializing is completely incompatible with
                    // all the possible variants (e.g. deserializing from boolean).
                    0 -> Content(_json = json)
                    1 -> bestMatches.single()
                    // If there's more than one match with the highest validity, then use the first
                    // completely valid match, or simply the first match if none are completely
                    // valid.
                    else -> bestMatches.firstOrNull { it.isValid() } ?: bestMatches.first()
                }
            }
        }

        internal class Serializer : BaseSerializer<Content>(Content::class) {

            override fun serialize(
                value: Content,
                generator: JsonGenerator,
                provider: SerializerProvider,
            ) {
                when {
                    value.string != null -> generator.writeObject(value.string)
                    value.chatCompletionRequestAssistantMessageContentArray != null ->
                        generator.writeObject(
                            value.chatCompletionRequestAssistantMessageContentArray
                        )
                    value._json != null -> generator.writeObject(value._json)
                    else -> throw IllegalStateException("Invalid Content")
                }
            }
        }

        /**
         * Learn about [text inputs](/docs/guides/text-generation).
         *
         * Fields:
         * - type (required): Literal["text"]
         * - text (required): str
         */
        @JsonDeserialize(using = UnnamedSchemaWithArrayParent1.Deserializer::class)
        @JsonSerialize(using = UnnamedSchemaWithArrayParent1.Serializer::class)
        class UnnamedSchemaWithArrayParent1
        private constructor(
            private val text: ChatCompletionContentPartTextParam? = null,
            private val refusal: ChatCompletionContentPartRefusalParam? = null,
            private val _json: JsonValue? = null,
        ) {

            /**
             * Learn about [text inputs](/docs/guides/text-generation).
             *
             * Fields:
             * - type (required): Literal["text"]
             * - text (required): str
             */
            fun text(): ChatCompletionContentPartTextParam? = text

            /**
             * Schema for ChatCompletionRequestMessageContentPartRefusal.
             *
             * Fields:
             * - type (required): Literal["refusal"]
             * - refusal (required): str
             */
            fun refusal(): ChatCompletionContentPartRefusalParam? = refusal

            fun isText(): Boolean = text != null

            fun isRefusal(): Boolean = refusal != null

            /**
             * Learn about [text inputs](/docs/guides/text-generation).
             *
             * Fields:
             * - type (required): Literal["text"]
             * - text (required): str
             */
            fun asText(): ChatCompletionContentPartTextParam = text.getOrThrow("text")

            /**
             * Schema for ChatCompletionRequestMessageContentPartRefusal.
             *
             * Fields:
             * - type (required): Literal["refusal"]
             * - refusal (required): str
             */
            fun asRefusal(): ChatCompletionContentPartRefusalParam = refusal.getOrThrow("refusal")

            fun _json(): JsonValue? = _json

            /**
             * Maps this instance's current variant to a value of type [T] using the given
             * [visitor].
             *
             * Note that this method is _not_ forwards compatible with new variants from the API,
             * unless [visitor] overrides [Visitor.unknown]. To handle variants not known to this
             * version of the SDK gracefully, consider overriding [Visitor.unknown]:
             * ```kotlin
             * import com.dedalus_sdk.api.core.JsonValue
             *
             * val result: String? = unnamedSchemaWithArrayParent1.accept(object : UnnamedSchemaWithArrayParent1.Visitor<String?> {
             *     override fun visitText(text: ChatCompletionContentPartTextParam): String? = text.toString()
             *
             *     // ...
             *
             *     override fun unknown(json: JsonValue?): String? {
             *         // Or inspect the `json`.
             *         return null
             *     }
             * })
             * ```
             *
             * @throws DedalusInvalidDataException if [Visitor.unknown] is not overridden in
             *   [visitor] and the current variant is unknown.
             */
            fun <T> accept(visitor: Visitor<T>): T =
                when {
                    text != null -> visitor.visitText(text)
                    refusal != null -> visitor.visitRefusal(refusal)
                    else -> visitor.unknown(_json)
                }

            private var validated: Boolean = false

            /**
             * Validates that the types of all values in this object match their expected types
             * recursively.
             *
             * This method is _not_ forwards compatible with new types from the API for existing
             * fields.
             *
             * @throws DedalusInvalidDataException if any value type in this object doesn't match
             *   its expected type.
             */
            fun validate(): UnnamedSchemaWithArrayParent1 = apply {
                if (validated) {
                    return@apply
                }

                accept(
                    object : Visitor<Unit> {
                        override fun visitText(text: ChatCompletionContentPartTextParam) {
                            text.validate()
                        }

                        override fun visitRefusal(refusal: ChatCompletionContentPartRefusalParam) {
                            refusal.validate()
                        }
                    }
                )
                validated = true
            }

            fun isValid(): Boolean =
                try {
                    validate()
                    true
                } catch (e: DedalusInvalidDataException) {
                    false
                }

            /**
             * Returns a score indicating how many valid values are contained in this object
             * recursively.
             *
             * Used for best match union deserialization.
             */
            internal fun validity(): Int =
                accept(
                    object : Visitor<Int> {
                        override fun visitText(text: ChatCompletionContentPartTextParam) =
                            text.validity()

                        override fun visitRefusal(refusal: ChatCompletionContentPartRefusalParam) =
                            refusal.validity()

                        override fun unknown(json: JsonValue?) = 0
                    }
                )

            override fun equals(other: Any?): Boolean {
                if (this === other) {
                    return true
                }

                return other is UnnamedSchemaWithArrayParent1 &&
                    text == other.text &&
                    refusal == other.refusal
            }

            override fun hashCode(): Int = Objects.hash(text, refusal)

            override fun toString(): String =
                when {
                    text != null -> "UnnamedSchemaWithArrayParent1{text=$text}"
                    refusal != null -> "UnnamedSchemaWithArrayParent1{refusal=$refusal}"
                    _json != null -> "UnnamedSchemaWithArrayParent1{_unknown=$_json}"
                    else -> throw IllegalStateException("Invalid UnnamedSchemaWithArrayParent1")
                }

            companion object {

                /**
                 * Learn about [text inputs](/docs/guides/text-generation).
                 *
                 * Fields:
                 * - type (required): Literal["text"]
                 * - text (required): str
                 */
                fun ofText(text: ChatCompletionContentPartTextParam) =
                    UnnamedSchemaWithArrayParent1(text = text)

                /**
                 * Schema for ChatCompletionRequestMessageContentPartRefusal.
                 *
                 * Fields:
                 * - type (required): Literal["refusal"]
                 * - refusal (required): str
                 */
                fun ofRefusal(refusal: ChatCompletionContentPartRefusalParam) =
                    UnnamedSchemaWithArrayParent1(refusal = refusal)
            }

            /**
             * An interface that defines how to map each variant of [UnnamedSchemaWithArrayParent1]
             * to a value of type [T].
             */
            interface Visitor<out T> {

                /**
                 * Learn about [text inputs](/docs/guides/text-generation).
                 *
                 * Fields:
                 * - type (required): Literal["text"]
                 * - text (required): str
                 */
                fun visitText(text: ChatCompletionContentPartTextParam): T

                /**
                 * Schema for ChatCompletionRequestMessageContentPartRefusal.
                 *
                 * Fields:
                 * - type (required): Literal["refusal"]
                 * - refusal (required): str
                 */
                fun visitRefusal(refusal: ChatCompletionContentPartRefusalParam): T

                /**
                 * Maps an unknown variant of [UnnamedSchemaWithArrayParent1] to a value of type
                 * [T].
                 *
                 * An instance of [UnnamedSchemaWithArrayParent1] can contain an unknown variant if
                 * it was deserialized from data that doesn't match any known variant. For example,
                 * if the SDK is on an older version than the API, then the API may respond with new
                 * variants that the SDK is unaware of.
                 *
                 * @throws DedalusInvalidDataException in the default implementation.
                 */
                fun unknown(json: JsonValue?): T {
                    throw DedalusInvalidDataException(
                        "Unknown UnnamedSchemaWithArrayParent1: $json"
                    )
                }
            }

            internal class Deserializer :
                BaseDeserializer<UnnamedSchemaWithArrayParent1>(
                    UnnamedSchemaWithArrayParent1::class
                ) {

                override fun ObjectCodec.deserialize(
                    node: JsonNode
                ): UnnamedSchemaWithArrayParent1 {
                    val json = JsonValue.fromJsonNode(node)
                    val type = json.asObject()?.get("type")?.asString()

                    when (type) {
                        "text" -> {
                            return tryDeserialize(
                                    node,
                                    jacksonTypeRef<ChatCompletionContentPartTextParam>(),
                                )
                                ?.let { UnnamedSchemaWithArrayParent1(text = it, _json = json) }
                                ?: UnnamedSchemaWithArrayParent1(_json = json)
                        }
                        "refusal" -> {
                            return tryDeserialize(
                                    node,
                                    jacksonTypeRef<ChatCompletionContentPartRefusalParam>(),
                                )
                                ?.let { UnnamedSchemaWithArrayParent1(refusal = it, _json = json) }
                                ?: UnnamedSchemaWithArrayParent1(_json = json)
                        }
                    }

                    return UnnamedSchemaWithArrayParent1(_json = json)
                }
            }

            internal class Serializer :
                BaseSerializer<UnnamedSchemaWithArrayParent1>(
                    UnnamedSchemaWithArrayParent1::class
                ) {

                override fun serialize(
                    value: UnnamedSchemaWithArrayParent1,
                    generator: JsonGenerator,
                    provider: SerializerProvider,
                ) {
                    when {
                        value.text != null -> generator.writeObject(value.text)
                        value.refusal != null -> generator.writeObject(value.refusal)
                        value._json != null -> generator.writeObject(value._json)
                        else -> throw IllegalStateException("Invalid UnnamedSchemaWithArrayParent1")
                    }
                }
            }
        }
    }

    /**
     * Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be
     * called, as generated by the model.
     *
     * Fields:
     * - arguments (required): str
     * - name (required): str
     */
    class FunctionCall
    @JsonCreator(mode = JsonCreator.Mode.DISABLED)
    private constructor(
        private val arguments: JsonField<String>,
        private val name: JsonField<String>,
        private val additionalProperties: MutableMap<String, JsonValue>,
    ) {

        @JsonCreator
        private constructor(
            @JsonProperty("arguments")
            @ExcludeMissing
            arguments: JsonField<String> = JsonMissing.of(),
            @JsonProperty("name") @ExcludeMissing name: JsonField<String> = JsonMissing.of(),
        ) : this(arguments, name, mutableMapOf())

        /**
         * The arguments to call the function with, as generated by the model in JSON format. Note
         * that the model does not always generate valid JSON, and may hallucinate parameters not
         * defined by your function schema. Validate the arguments in your code before calling your
         * function.
         *
         * @throws DedalusInvalidDataException if the JSON field has an unexpected type or is
         *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
         */
        fun arguments(): String = arguments.getRequired("arguments")

        /**
         * The name of the function to call.
         *
         * @throws DedalusInvalidDataException if the JSON field has an unexpected type or is
         *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
         */
        fun name(): String = name.getRequired("name")

        /**
         * Returns the raw JSON value of [arguments].
         *
         * Unlike [arguments], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("arguments") @ExcludeMissing fun _arguments(): JsonField<String> = arguments

        /**
         * Returns the raw JSON value of [name].
         *
         * Unlike [name], this method doesn't throw if the JSON field has an unexpected type.
         */
        @JsonProperty("name") @ExcludeMissing fun _name(): JsonField<String> = name

        @JsonAnySetter
        private fun putAdditionalProperty(key: String, value: JsonValue) {
            additionalProperties.put(key, value)
        }

        @JsonAnyGetter
        @ExcludeMissing
        fun _additionalProperties(): Map<String, JsonValue> =
            Collections.unmodifiableMap(additionalProperties)

        fun toBuilder() = Builder().from(this)

        companion object {

            /**
             * Returns a mutable builder for constructing an instance of [FunctionCall].
             *
             * The following fields are required:
             * ```kotlin
             * .arguments()
             * .name()
             * ```
             */
            fun builder() = Builder()
        }

        /** A builder for [FunctionCall]. */
        class Builder internal constructor() {

            private var arguments: JsonField<String>? = null
            private var name: JsonField<String>? = null
            private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

            internal fun from(functionCall: FunctionCall) = apply {
                arguments = functionCall.arguments
                name = functionCall.name
                additionalProperties = functionCall.additionalProperties.toMutableMap()
            }

            /**
             * The arguments to call the function with, as generated by the model in JSON format.
             * Note that the model does not always generate valid JSON, and may hallucinate
             * parameters not defined by your function schema. Validate the arguments in your code
             * before calling your function.
             */
            fun arguments(arguments: String) = arguments(JsonField.of(arguments))

            /**
             * Sets [Builder.arguments] to an arbitrary JSON value.
             *
             * You should usually call [Builder.arguments] with a well-typed [String] value instead.
             * This method is primarily for setting the field to an undocumented or not yet
             * supported value.
             */
            fun arguments(arguments: JsonField<String>) = apply { this.arguments = arguments }

            /** The name of the function to call. */
            fun name(name: String) = name(JsonField.of(name))

            /**
             * Sets [Builder.name] to an arbitrary JSON value.
             *
             * You should usually call [Builder.name] with a well-typed [String] value instead. This
             * method is primarily for setting the field to an undocumented or not yet supported
             * value.
             */
            fun name(name: JsonField<String>) = apply { this.name = name }

            fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.clear()
                putAllAdditionalProperties(additionalProperties)
            }

            fun putAdditionalProperty(key: String, value: JsonValue) = apply {
                additionalProperties.put(key, value)
            }

            fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.putAll(additionalProperties)
            }

            fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

            fun removeAllAdditionalProperties(keys: Set<String>) = apply {
                keys.forEach(::removeAdditionalProperty)
            }

            /**
             * Returns an immutable instance of [FunctionCall].
             *
             * Further updates to this [Builder] will not mutate the returned instance.
             *
             * The following fields are required:
             * ```kotlin
             * .arguments()
             * .name()
             * ```
             *
             * @throws IllegalStateException if any required field is unset.
             */
            fun build(): FunctionCall =
                FunctionCall(
                    checkRequired("arguments", arguments),
                    checkRequired("name", name),
                    additionalProperties.toMutableMap(),
                )
        }

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws DedalusInvalidDataException if any value type in this object doesn't match its
         *   expected type.
         */
        fun validate(): FunctionCall = apply {
            if (validated) {
                return@apply
            }

            arguments()
            name()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: DedalusInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        internal fun validity(): Int =
            (if (arguments.asKnown() == null) 0 else 1) + (if (name.asKnown() == null) 0 else 1)

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is FunctionCall &&
                arguments == other.arguments &&
                name == other.name &&
                additionalProperties == other.additionalProperties
        }

        private val hashCode: Int by lazy { Objects.hash(arguments, name, additionalProperties) }

        override fun hashCode(): Int = hashCode

        override fun toString() =
            "FunctionCall{arguments=$arguments, name=$name, additionalProperties=$additionalProperties}"
    }

    /**
     * A call to a function tool created by the model.
     *
     * Fields:
     * - id (required): str
     * - type (required): Literal["function"]
     * - function (required): ChatCompletionMessageToolCallFunction
     * - thought_signature (optional): str
     */
    @JsonDeserialize(using = ToolCall.Deserializer::class)
    @JsonSerialize(using = ToolCall.Serializer::class)
    class ToolCall
    private constructor(
        private val function: ChatCompletionMessageToolCall? = null,
        private val custom: ChatCompletionMessageCustomToolCall? = null,
        private val _json: JsonValue? = null,
    ) {

        /**
         * A call to a function tool created by the model.
         *
         * Fields:
         * - id (required): str
         * - type (required): Literal["function"]
         * - function (required): ChatCompletionMessageToolCallFunction
         * - thought_signature (optional): str
         */
        fun function(): ChatCompletionMessageToolCall? = function

        /**
         * A call to a custom tool created by the model.
         *
         * Fields:
         * - id (required): str
         * - type (required): Literal["custom"]
         * - custom (required): ChatCompletionMessageCustomToolCallCustom
         */
        fun custom(): ChatCompletionMessageCustomToolCall? = custom

        fun isFunction(): Boolean = function != null

        fun isCustom(): Boolean = custom != null

        /**
         * A call to a function tool created by the model.
         *
         * Fields:
         * - id (required): str
         * - type (required): Literal["function"]
         * - function (required): ChatCompletionMessageToolCallFunction
         * - thought_signature (optional): str
         */
        fun asFunction(): ChatCompletionMessageToolCall = function.getOrThrow("function")

        /**
         * A call to a custom tool created by the model.
         *
         * Fields:
         * - id (required): str
         * - type (required): Literal["custom"]
         * - custom (required): ChatCompletionMessageCustomToolCallCustom
         */
        fun asCustom(): ChatCompletionMessageCustomToolCall = custom.getOrThrow("custom")

        fun _json(): JsonValue? = _json

        /**
         * Maps this instance's current variant to a value of type [T] using the given [visitor].
         *
         * Note that this method is _not_ forwards compatible with new variants from the API, unless
         * [visitor] overrides [Visitor.unknown]. To handle variants not known to this version of
         * the SDK gracefully, consider overriding [Visitor.unknown]:
         * ```kotlin
         * import com.dedalus_sdk.api.core.JsonValue
         *
         * val result: String? = toolCall.accept(object : ToolCall.Visitor<String?> {
         *     override fun visitFunction(function: ChatCompletionMessageToolCall): String? = function.toString()
         *
         *     // ...
         *
         *     override fun unknown(json: JsonValue?): String? {
         *         // Or inspect the `json`.
         *         return null
         *     }
         * })
         * ```
         *
         * @throws DedalusInvalidDataException if [Visitor.unknown] is not overridden in [visitor]
         *   and the current variant is unknown.
         */
        fun <T> accept(visitor: Visitor<T>): T =
            when {
                function != null -> visitor.visitFunction(function)
                custom != null -> visitor.visitCustom(custom)
                else -> visitor.unknown(_json)
            }

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws DedalusInvalidDataException if any value type in this object doesn't match its
         *   expected type.
         */
        fun validate(): ToolCall = apply {
            if (validated) {
                return@apply
            }

            accept(
                object : Visitor<Unit> {
                    override fun visitFunction(function: ChatCompletionMessageToolCall) {
                        function.validate()
                    }

                    override fun visitCustom(custom: ChatCompletionMessageCustomToolCall) {
                        custom.validate()
                    }
                }
            )
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: DedalusInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        internal fun validity(): Int =
            accept(
                object : Visitor<Int> {
                    override fun visitFunction(function: ChatCompletionMessageToolCall) =
                        function.validity()

                    override fun visitCustom(custom: ChatCompletionMessageCustomToolCall) =
                        custom.validity()

                    override fun unknown(json: JsonValue?) = 0
                }
            )

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is ToolCall && function == other.function && custom == other.custom
        }

        override fun hashCode(): Int = Objects.hash(function, custom)

        override fun toString(): String =
            when {
                function != null -> "ToolCall{function=$function}"
                custom != null -> "ToolCall{custom=$custom}"
                _json != null -> "ToolCall{_unknown=$_json}"
                else -> throw IllegalStateException("Invalid ToolCall")
            }

        companion object {

            /**
             * A call to a function tool created by the model.
             *
             * Fields:
             * - id (required): str
             * - type (required): Literal["function"]
             * - function (required): ChatCompletionMessageToolCallFunction
             * - thought_signature (optional): str
             */
            fun ofFunction(function: ChatCompletionMessageToolCall) = ToolCall(function = function)

            /**
             * A call to a custom tool created by the model.
             *
             * Fields:
             * - id (required): str
             * - type (required): Literal["custom"]
             * - custom (required): ChatCompletionMessageCustomToolCallCustom
             */
            fun ofCustom(custom: ChatCompletionMessageCustomToolCall) = ToolCall(custom = custom)
        }

        /**
         * An interface that defines how to map each variant of [ToolCall] to a value of type [T].
         */
        interface Visitor<out T> {

            /**
             * A call to a function tool created by the model.
             *
             * Fields:
             * - id (required): str
             * - type (required): Literal["function"]
             * - function (required): ChatCompletionMessageToolCallFunction
             * - thought_signature (optional): str
             */
            fun visitFunction(function: ChatCompletionMessageToolCall): T

            /**
             * A call to a custom tool created by the model.
             *
             * Fields:
             * - id (required): str
             * - type (required): Literal["custom"]
             * - custom (required): ChatCompletionMessageCustomToolCallCustom
             */
            fun visitCustom(custom: ChatCompletionMessageCustomToolCall): T

            /**
             * Maps an unknown variant of [ToolCall] to a value of type [T].
             *
             * An instance of [ToolCall] can contain an unknown variant if it was deserialized from
             * data that doesn't match any known variant. For example, if the SDK is on an older
             * version than the API, then the API may respond with new variants that the SDK is
             * unaware of.
             *
             * @throws DedalusInvalidDataException in the default implementation.
             */
            fun unknown(json: JsonValue?): T {
                throw DedalusInvalidDataException("Unknown ToolCall: $json")
            }
        }

        internal class Deserializer : BaseDeserializer<ToolCall>(ToolCall::class) {

            override fun ObjectCodec.deserialize(node: JsonNode): ToolCall {
                val json = JsonValue.fromJsonNode(node)
                val type = json.asObject()?.get("type")?.asString()

                when (type) {
                    "function" -> {
                        return tryDeserialize(node, jacksonTypeRef<ChatCompletionMessageToolCall>())
                            ?.let { ToolCall(function = it, _json = json) }
                            ?: ToolCall(_json = json)
                    }
                    "custom" -> {
                        return tryDeserialize(
                                node,
                                jacksonTypeRef<ChatCompletionMessageCustomToolCall>(),
                            )
                            ?.let { ToolCall(custom = it, _json = json) } ?: ToolCall(_json = json)
                    }
                }

                return ToolCall(_json = json)
            }
        }

        internal class Serializer : BaseSerializer<ToolCall>(ToolCall::class) {

            override fun serialize(
                value: ToolCall,
                generator: JsonGenerator,
                provider: SerializerProvider,
            ) {
                when {
                    value.function != null -> generator.writeObject(value.function)
                    value.custom != null -> generator.writeObject(value.custom)
                    value._json != null -> generator.writeObject(value._json)
                    else -> throw IllegalStateException("Invalid ToolCall")
                }
            }
        }
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is ChatCompletionAssistantMessageParam &&
            role == other.role &&
            audio == other.audio &&
            content == other.content &&
            functionCall == other.functionCall &&
            name == other.name &&
            refusal == other.refusal &&
            toolCalls == other.toolCalls &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(
            role,
            audio,
            content,
            functionCall,
            name,
            refusal,
            toolCalls,
            additionalProperties,
        )
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "ChatCompletionAssistantMessageParam{role=$role, audio=$audio, content=$content, functionCall=$functionCall, name=$name, refusal=$refusal, toolCalls=$toolCalls, additionalProperties=$additionalProperties}"
}
