// File generated from our OpenAPI spec by Stainless.

package com.dedalus_sdk.api.models.chat.completions

import com.dedalus_sdk.api.core.Enum
import com.dedalus_sdk.api.core.ExcludeMissing
import com.dedalus_sdk.api.core.JsonField
import com.dedalus_sdk.api.core.JsonMissing
import com.dedalus_sdk.api.core.JsonValue
import com.dedalus_sdk.api.core.checkRequired
import com.dedalus_sdk.api.errors.DedalusInvalidDataException
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import java.util.Collections
import java.util.Objects

/**
 * A chat completion choice.
 *
 * OpenAI-compatible choice object for non-streaming responses. Part of the ChatCompletion response.
 */
class Choice
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val index: JsonField<Long>,
    private val message: JsonField<ChatCompletionMessage>,
    private val finishReason: JsonField<FinishReason>,
    private val logprobs: JsonField<ChoiceLogprobs>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("index") @ExcludeMissing index: JsonField<Long> = JsonMissing.of(),
        @JsonProperty("message")
        @ExcludeMissing
        message: JsonField<ChatCompletionMessage> = JsonMissing.of(),
        @JsonProperty("finish_reason")
        @ExcludeMissing
        finishReason: JsonField<FinishReason> = JsonMissing.of(),
        @JsonProperty("logprobs")
        @ExcludeMissing
        logprobs: JsonField<ChoiceLogprobs> = JsonMissing.of(),
    ) : this(index, message, finishReason, logprobs, mutableMapOf())

    /**
     * The index of the choice in the list of choices.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun index(): Long = index.getRequired("index")

    /**
     * A chat completion message generated by the model.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun message(): ChatCompletionMessage = message.getRequired("message")

    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a
     * natural stop point or a provided stop sequence, `length` if the maximum number of tokens
     * specified in the request was reached, `content_filter` if content was omitted due to a flag
     * from our content filters, `tool_calls` if the model called a tool, or `function_call`
     * (deprecated) if the model called a function.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun finishReason(): FinishReason? = finishReason.getNullable("finish_reason")

    /**
     * Log probability information for the choice.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun logprobs(): ChoiceLogprobs? = logprobs.getNullable("logprobs")

    /**
     * Returns the raw JSON value of [index].
     *
     * Unlike [index], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("index") @ExcludeMissing fun _index(): JsonField<Long> = index

    /**
     * Returns the raw JSON value of [message].
     *
     * Unlike [message], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("message")
    @ExcludeMissing
    fun _message(): JsonField<ChatCompletionMessage> = message

    /**
     * Returns the raw JSON value of [finishReason].
     *
     * Unlike [finishReason], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("finish_reason")
    @ExcludeMissing
    fun _finishReason(): JsonField<FinishReason> = finishReason

    /**
     * Returns the raw JSON value of [logprobs].
     *
     * Unlike [logprobs], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("logprobs") @ExcludeMissing fun _logprobs(): JsonField<ChoiceLogprobs> = logprobs

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [Choice].
         *
         * The following fields are required:
         * ```kotlin
         * .index()
         * .message()
         * ```
         */
        fun builder() = Builder()
    }

    /** A builder for [Choice]. */
    class Builder internal constructor() {

        private var index: JsonField<Long>? = null
        private var message: JsonField<ChatCompletionMessage>? = null
        private var finishReason: JsonField<FinishReason> = JsonMissing.of()
        private var logprobs: JsonField<ChoiceLogprobs> = JsonMissing.of()
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        internal fun from(choice: Choice) = apply {
            index = choice.index
            message = choice.message
            finishReason = choice.finishReason
            logprobs = choice.logprobs
            additionalProperties = choice.additionalProperties.toMutableMap()
        }

        /** The index of the choice in the list of choices. */
        fun index(index: Long) = index(JsonField.of(index))

        /**
         * Sets [Builder.index] to an arbitrary JSON value.
         *
         * You should usually call [Builder.index] with a well-typed [Long] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun index(index: JsonField<Long>) = apply { this.index = index }

        /** A chat completion message generated by the model. */
        fun message(message: ChatCompletionMessage) = message(JsonField.of(message))

        /**
         * Sets [Builder.message] to an arbitrary JSON value.
         *
         * You should usually call [Builder.message] with a well-typed [ChatCompletionMessage] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun message(message: JsonField<ChatCompletionMessage>) = apply { this.message = message }

        /**
         * The reason the model stopped generating tokens. This will be `stop` if the model hit a
         * natural stop point or a provided stop sequence, `length` if the maximum number of tokens
         * specified in the request was reached, `content_filter` if content was omitted due to a
         * flag from our content filters, `tool_calls` if the model called a tool, or
         * `function_call` (deprecated) if the model called a function.
         */
        fun finishReason(finishReason: FinishReason?) =
            finishReason(JsonField.ofNullable(finishReason))

        /**
         * Sets [Builder.finishReason] to an arbitrary JSON value.
         *
         * You should usually call [Builder.finishReason] with a well-typed [FinishReason] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun finishReason(finishReason: JsonField<FinishReason>) = apply {
            this.finishReason = finishReason
        }

        /** Log probability information for the choice. */
        fun logprobs(logprobs: ChoiceLogprobs?) = logprobs(JsonField.ofNullable(logprobs))

        /**
         * Sets [Builder.logprobs] to an arbitrary JSON value.
         *
         * You should usually call [Builder.logprobs] with a well-typed [ChoiceLogprobs] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun logprobs(logprobs: JsonField<ChoiceLogprobs>) = apply { this.logprobs = logprobs }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [Choice].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```kotlin
         * .index()
         * .message()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): Choice =
            Choice(
                checkRequired("index", index),
                checkRequired("message", message),
                finishReason,
                logprobs,
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws DedalusInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): Choice = apply {
        if (validated) {
            return@apply
        }

        index()
        message().validate()
        finishReason()?.validate()
        logprobs()?.validate()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: DedalusInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    internal fun validity(): Int =
        (if (index.asKnown() == null) 0 else 1) +
            (message.asKnown()?.validity() ?: 0) +
            (finishReason.asKnown()?.validity() ?: 0) +
            (logprobs.asKnown()?.validity() ?: 0)

    /**
     * The reason the model stopped generating tokens. This will be `stop` if the model hit a
     * natural stop point or a provided stop sequence, `length` if the maximum number of tokens
     * specified in the request was reached, `content_filter` if content was omitted due to a flag
     * from our content filters, `tool_calls` if the model called a tool, or `function_call`
     * (deprecated) if the model called a function.
     */
    class FinishReason @JsonCreator private constructor(private val value: JsonField<String>) :
        Enum {

        /**
         * Returns this class instance's raw value.
         *
         * This is usually only useful if this instance was deserialized from data that doesn't
         * match any known member, and you want to know that value. For example, if the SDK is on an
         * older version than the API, then the API may respond with new members that the SDK is
         * unaware of.
         */
        @com.fasterxml.jackson.annotation.JsonValue fun _value(): JsonField<String> = value

        companion object {

            val STOP = of("stop")

            val LENGTH = of("length")

            val TOOL_CALLS = of("tool_calls")

            val CONTENT_FILTER = of("content_filter")

            val FUNCTION_CALL = of("function_call")

            fun of(value: String) = FinishReason(JsonField.of(value))
        }

        /** An enum containing [FinishReason]'s known values. */
        enum class Known {
            STOP,
            LENGTH,
            TOOL_CALLS,
            CONTENT_FILTER,
            FUNCTION_CALL,
        }

        /**
         * An enum containing [FinishReason]'s known values, as well as an [_UNKNOWN] member.
         *
         * An instance of [FinishReason] can contain an unknown value in a couple of cases:
         * - It was deserialized from data that doesn't match any known member. For example, if the
         *   SDK is on an older version than the API, then the API may respond with new members that
         *   the SDK is unaware of.
         * - It was constructed with an arbitrary value using the [of] method.
         */
        enum class Value {
            STOP,
            LENGTH,
            TOOL_CALLS,
            CONTENT_FILTER,
            FUNCTION_CALL,
            /**
             * An enum member indicating that [FinishReason] was instantiated with an unknown value.
             */
            _UNKNOWN,
        }

        /**
         * Returns an enum member corresponding to this class instance's value, or [Value._UNKNOWN]
         * if the class was instantiated with an unknown value.
         *
         * Use the [known] method instead if you're certain the value is always known or if you want
         * to throw for the unknown case.
         */
        fun value(): Value =
            when (this) {
                STOP -> Value.STOP
                LENGTH -> Value.LENGTH
                TOOL_CALLS -> Value.TOOL_CALLS
                CONTENT_FILTER -> Value.CONTENT_FILTER
                FUNCTION_CALL -> Value.FUNCTION_CALL
                else -> Value._UNKNOWN
            }

        /**
         * Returns an enum member corresponding to this class instance's value.
         *
         * Use the [value] method instead if you're uncertain the value is always known and don't
         * want to throw for the unknown case.
         *
         * @throws DedalusInvalidDataException if this class instance's value is a not a known
         *   member.
         */
        fun known(): Known =
            when (this) {
                STOP -> Known.STOP
                LENGTH -> Known.LENGTH
                TOOL_CALLS -> Known.TOOL_CALLS
                CONTENT_FILTER -> Known.CONTENT_FILTER
                FUNCTION_CALL -> Known.FUNCTION_CALL
                else -> throw DedalusInvalidDataException("Unknown FinishReason: $value")
            }

        /**
         * Returns this class instance's primitive wire representation.
         *
         * This differs from the [toString] method because that method is primarily for debugging
         * and generally doesn't throw.
         *
         * @throws DedalusInvalidDataException if this class instance's value does not have the
         *   expected primitive type.
         */
        fun asString(): String =
            _value().asString() ?: throw DedalusInvalidDataException("Value is not a String")

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws DedalusInvalidDataException if any value type in this object doesn't match its
         *   expected type.
         */
        fun validate(): FinishReason = apply {
            if (validated) {
                return@apply
            }

            known()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: DedalusInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        internal fun validity(): Int = if (value() == Value._UNKNOWN) 0 else 1

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is FinishReason && value == other.value
        }

        override fun hashCode() = value.hashCode()

        override fun toString() = value.toString()
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is Choice &&
            index == other.index &&
            message == other.message &&
            finishReason == other.finishReason &&
            logprobs == other.logprobs &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(index, message, finishReason, logprobs, additionalProperties)
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "Choice{index=$index, message=$message, finishReason=$finishReason, logprobs=$logprobs, additionalProperties=$additionalProperties}"
}
