// File generated from our OpenAPI spec by Stainless.

package com.dedalus_sdk.api.models.chat.completions

import com.dedalus_sdk.api.core.ExcludeMissing
import com.dedalus_sdk.api.core.JsonField
import com.dedalus_sdk.api.core.JsonMissing
import com.dedalus_sdk.api.core.JsonValue
import com.dedalus_sdk.api.errors.DedalusInvalidDataException
import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import java.util.Collections
import java.util.Objects

/**
 * Breakdown of tokens used in a completion.
 *
 * Fields:
 * - accepted_prediction_tokens (optional): int
 * - audio_tokens (optional): int
 * - reasoning_tokens (optional): int
 * - rejected_prediction_tokens (optional): int
 */
class CompletionTokensDetails
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val acceptedPredictionTokens: JsonField<Long>,
    private val audioTokens: JsonField<Long>,
    private val reasoningTokens: JsonField<Long>,
    private val rejectedPredictionTokens: JsonField<Long>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("accepted_prediction_tokens")
        @ExcludeMissing
        acceptedPredictionTokens: JsonField<Long> = JsonMissing.of(),
        @JsonProperty("audio_tokens")
        @ExcludeMissing
        audioTokens: JsonField<Long> = JsonMissing.of(),
        @JsonProperty("reasoning_tokens")
        @ExcludeMissing
        reasoningTokens: JsonField<Long> = JsonMissing.of(),
        @JsonProperty("rejected_prediction_tokens")
        @ExcludeMissing
        rejectedPredictionTokens: JsonField<Long> = JsonMissing.of(),
    ) : this(
        acceptedPredictionTokens,
        audioTokens,
        reasoningTokens,
        rejectedPredictionTokens,
        mutableMapOf(),
    )

    /**
     * When using Predicted Outputs, the number of tokens in the prediction that appeared in the
     * completion.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun acceptedPredictionTokens(): Long? =
        acceptedPredictionTokens.getNullable("accepted_prediction_tokens")

    /**
     * Audio input tokens generated by the model.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun audioTokens(): Long? = audioTokens.getNullable("audio_tokens")

    /**
     * Tokens generated by the model for reasoning.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun reasoningTokens(): Long? = reasoningTokens.getNullable("reasoning_tokens")

    /**
     * When using Predicted Outputs, the number of tokens in the prediction that did not appear in
     * the completion. However, like reasoning tokens, these tokens are still counted in the total
     * completion tokens for purposes of billing, output, and context window limits.
     *
     * @throws DedalusInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun rejectedPredictionTokens(): Long? =
        rejectedPredictionTokens.getNullable("rejected_prediction_tokens")

    /**
     * Returns the raw JSON value of [acceptedPredictionTokens].
     *
     * Unlike [acceptedPredictionTokens], this method doesn't throw if the JSON field has an
     * unexpected type.
     */
    @JsonProperty("accepted_prediction_tokens")
    @ExcludeMissing
    fun _acceptedPredictionTokens(): JsonField<Long> = acceptedPredictionTokens

    /**
     * Returns the raw JSON value of [audioTokens].
     *
     * Unlike [audioTokens], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("audio_tokens") @ExcludeMissing fun _audioTokens(): JsonField<Long> = audioTokens

    /**
     * Returns the raw JSON value of [reasoningTokens].
     *
     * Unlike [reasoningTokens], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("reasoning_tokens")
    @ExcludeMissing
    fun _reasoningTokens(): JsonField<Long> = reasoningTokens

    /**
     * Returns the raw JSON value of [rejectedPredictionTokens].
     *
     * Unlike [rejectedPredictionTokens], this method doesn't throw if the JSON field has an
     * unexpected type.
     */
    @JsonProperty("rejected_prediction_tokens")
    @ExcludeMissing
    fun _rejectedPredictionTokens(): JsonField<Long> = rejectedPredictionTokens

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /** Returns a mutable builder for constructing an instance of [CompletionTokensDetails]. */
        fun builder() = Builder()
    }

    /** A builder for [CompletionTokensDetails]. */
    class Builder internal constructor() {

        private var acceptedPredictionTokens: JsonField<Long> = JsonMissing.of()
        private var audioTokens: JsonField<Long> = JsonMissing.of()
        private var reasoningTokens: JsonField<Long> = JsonMissing.of()
        private var rejectedPredictionTokens: JsonField<Long> = JsonMissing.of()
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        internal fun from(completionTokensDetails: CompletionTokensDetails) = apply {
            acceptedPredictionTokens = completionTokensDetails.acceptedPredictionTokens
            audioTokens = completionTokensDetails.audioTokens
            reasoningTokens = completionTokensDetails.reasoningTokens
            rejectedPredictionTokens = completionTokensDetails.rejectedPredictionTokens
            additionalProperties = completionTokensDetails.additionalProperties.toMutableMap()
        }

        /**
         * When using Predicted Outputs, the number of tokens in the prediction that appeared in the
         * completion.
         */
        fun acceptedPredictionTokens(acceptedPredictionTokens: Long) =
            acceptedPredictionTokens(JsonField.of(acceptedPredictionTokens))

        /**
         * Sets [Builder.acceptedPredictionTokens] to an arbitrary JSON value.
         *
         * You should usually call [Builder.acceptedPredictionTokens] with a well-typed [Long] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun acceptedPredictionTokens(acceptedPredictionTokens: JsonField<Long>) = apply {
            this.acceptedPredictionTokens = acceptedPredictionTokens
        }

        /** Audio input tokens generated by the model. */
        fun audioTokens(audioTokens: Long) = audioTokens(JsonField.of(audioTokens))

        /**
         * Sets [Builder.audioTokens] to an arbitrary JSON value.
         *
         * You should usually call [Builder.audioTokens] with a well-typed [Long] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun audioTokens(audioTokens: JsonField<Long>) = apply { this.audioTokens = audioTokens }

        /** Tokens generated by the model for reasoning. */
        fun reasoningTokens(reasoningTokens: Long) = reasoningTokens(JsonField.of(reasoningTokens))

        /**
         * Sets [Builder.reasoningTokens] to an arbitrary JSON value.
         *
         * You should usually call [Builder.reasoningTokens] with a well-typed [Long] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun reasoningTokens(reasoningTokens: JsonField<Long>) = apply {
            this.reasoningTokens = reasoningTokens
        }

        /**
         * When using Predicted Outputs, the number of tokens in the prediction that did not appear
         * in the completion. However, like reasoning tokens, these tokens are still counted in the
         * total completion tokens for purposes of billing, output, and context window limits.
         */
        fun rejectedPredictionTokens(rejectedPredictionTokens: Long) =
            rejectedPredictionTokens(JsonField.of(rejectedPredictionTokens))

        /**
         * Sets [Builder.rejectedPredictionTokens] to an arbitrary JSON value.
         *
         * You should usually call [Builder.rejectedPredictionTokens] with a well-typed [Long] value
         * instead. This method is primarily for setting the field to an undocumented or not yet
         * supported value.
         */
        fun rejectedPredictionTokens(rejectedPredictionTokens: JsonField<Long>) = apply {
            this.rejectedPredictionTokens = rejectedPredictionTokens
        }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [CompletionTokensDetails].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         */
        fun build(): CompletionTokensDetails =
            CompletionTokensDetails(
                acceptedPredictionTokens,
                audioTokens,
                reasoningTokens,
                rejectedPredictionTokens,
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws DedalusInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): CompletionTokensDetails = apply {
        if (validated) {
            return@apply
        }

        acceptedPredictionTokens()
        audioTokens()
        reasoningTokens()
        rejectedPredictionTokens()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: DedalusInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    internal fun validity(): Int =
        (if (acceptedPredictionTokens.asKnown() == null) 0 else 1) +
            (if (audioTokens.asKnown() == null) 0 else 1) +
            (if (reasoningTokens.asKnown() == null) 0 else 1) +
            (if (rejectedPredictionTokens.asKnown() == null) 0 else 1)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is CompletionTokensDetails &&
            acceptedPredictionTokens == other.acceptedPredictionTokens &&
            audioTokens == other.audioTokens &&
            reasoningTokens == other.reasoningTokens &&
            rejectedPredictionTokens == other.rejectedPredictionTokens &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(
            acceptedPredictionTokens,
            audioTokens,
            reasoningTokens,
            rejectedPredictionTokens,
            additionalProperties,
        )
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "CompletionTokensDetails{acceptedPredictionTokens=$acceptedPredictionTokens, audioTokens=$audioTokens, reasoningTokens=$reasoningTokens, rejectedPredictionTokens=$rejectedPredictionTokens, additionalProperties=$additionalProperties}"
}
