// File generated from our OpenAPI spec by Stainless.

package com.dedalus_sdk.api.models.chat.completions

import com.dedalus_sdk.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ChatCompletionChunkTest {

    @Test
    fun create() {
        val chatCompletionChunk =
            ChatCompletionChunk.builder()
                .id("id")
                .addChoice(
                    StreamChoice.builder()
                        .delta(
                            ChoiceDelta.builder()
                                .content("content")
                                .functionCall(
                                    ChoiceDelta.FunctionCall.builder()
                                        .arguments("arguments")
                                        .name("name")
                                        .build()
                                )
                                .refusal("refusal")
                                .role(ChoiceDelta.Role.DEVELOPER)
                                .addToolCall(
                                    ChoiceDeltaToolCall.builder()
                                        .index(0L)
                                        .id("id")
                                        .function(
                                            ChoiceDeltaToolCall.Function.builder()
                                                .arguments("arguments")
                                                .name("name")
                                                .build()
                                        )
                                        .type(ChoiceDeltaToolCall.Type.FUNCTION)
                                        .build()
                                )
                                .build()
                        )
                        .finishReason(StreamChoice.FinishReason.STOP)
                        .index(0L)
                        .logprobs(
                            StreamChoiceLogprobs.builder()
                                .addContent(
                                    ChatCompletionTokenLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionTokenLogprob.TopLogprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .addRefusal(
                                    ChatCompletionTokenLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionTokenLogprob.TopLogprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .created(0L)
                .model("model")
                .serviceTier(ChatCompletionChunk.ServiceTier.AUTO)
                .systemFingerprint("system_fingerprint")
                .usage(
                    CompletionUsage.builder()
                        .completionTokens(0L)
                        .promptTokens(0L)
                        .totalTokens(0L)
                        .completionTokensDetails(
                            CompletionTokensDetails.builder()
                                .acceptedPredictionTokens(0L)
                                .audioTokens(0L)
                                .reasoningTokens(0L)
                                .rejectedPredictionTokens(0L)
                                .build()
                        )
                        .promptTokensDetails(
                            PromptTokensDetails.builder().audioTokens(0L).cachedTokens(0L).build()
                        )
                        .build()
                )
                .build()

        assertThat(chatCompletionChunk.id()).isEqualTo("id")
        assertThat(chatCompletionChunk.choices())
            .containsExactly(
                StreamChoice.builder()
                    .delta(
                        ChoiceDelta.builder()
                            .content("content")
                            .functionCall(
                                ChoiceDelta.FunctionCall.builder()
                                    .arguments("arguments")
                                    .name("name")
                                    .build()
                            )
                            .refusal("refusal")
                            .role(ChoiceDelta.Role.DEVELOPER)
                            .addToolCall(
                                ChoiceDeltaToolCall.builder()
                                    .index(0L)
                                    .id("id")
                                    .function(
                                        ChoiceDeltaToolCall.Function.builder()
                                            .arguments("arguments")
                                            .name("name")
                                            .build()
                                    )
                                    .type(ChoiceDeltaToolCall.Type.FUNCTION)
                                    .build()
                            )
                            .build()
                    )
                    .finishReason(StreamChoice.FinishReason.STOP)
                    .index(0L)
                    .logprobs(
                        StreamChoiceLogprobs.builder()
                            .addContent(
                                ChatCompletionTokenLogprob.builder()
                                    .token("token")
                                    .addByte(0L)
                                    .logprob(0.0)
                                    .addTopLogprob(
                                        ChatCompletionTokenLogprob.TopLogprob.builder()
                                            .token("token")
                                            .addByte(0L)
                                            .logprob(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .addRefusal(
                                ChatCompletionTokenLogprob.builder()
                                    .token("token")
                                    .addByte(0L)
                                    .logprob(0.0)
                                    .addTopLogprob(
                                        ChatCompletionTokenLogprob.TopLogprob.builder()
                                            .token("token")
                                            .addByte(0L)
                                            .logprob(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(chatCompletionChunk.created()).isEqualTo(0L)
        assertThat(chatCompletionChunk.model()).isEqualTo("model")
        assertThat(chatCompletionChunk.serviceTier())
            .isEqualTo(ChatCompletionChunk.ServiceTier.AUTO)
        assertThat(chatCompletionChunk.systemFingerprint()).isEqualTo("system_fingerprint")
        assertThat(chatCompletionChunk.usage())
            .isEqualTo(
                CompletionUsage.builder()
                    .completionTokens(0L)
                    .promptTokens(0L)
                    .totalTokens(0L)
                    .completionTokensDetails(
                        CompletionTokensDetails.builder()
                            .acceptedPredictionTokens(0L)
                            .audioTokens(0L)
                            .reasoningTokens(0L)
                            .rejectedPredictionTokens(0L)
                            .build()
                    )
                    .promptTokensDetails(
                        PromptTokensDetails.builder().audioTokens(0L).cachedTokens(0L).build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val chatCompletionChunk =
            ChatCompletionChunk.builder()
                .id("id")
                .addChoice(
                    StreamChoice.builder()
                        .delta(
                            ChoiceDelta.builder()
                                .content("content")
                                .functionCall(
                                    ChoiceDelta.FunctionCall.builder()
                                        .arguments("arguments")
                                        .name("name")
                                        .build()
                                )
                                .refusal("refusal")
                                .role(ChoiceDelta.Role.DEVELOPER)
                                .addToolCall(
                                    ChoiceDeltaToolCall.builder()
                                        .index(0L)
                                        .id("id")
                                        .function(
                                            ChoiceDeltaToolCall.Function.builder()
                                                .arguments("arguments")
                                                .name("name")
                                                .build()
                                        )
                                        .type(ChoiceDeltaToolCall.Type.FUNCTION)
                                        .build()
                                )
                                .build()
                        )
                        .finishReason(StreamChoice.FinishReason.STOP)
                        .index(0L)
                        .logprobs(
                            StreamChoiceLogprobs.builder()
                                .addContent(
                                    ChatCompletionTokenLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionTokenLogprob.TopLogprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .addRefusal(
                                    ChatCompletionTokenLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionTokenLogprob.TopLogprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .created(0L)
                .model("model")
                .serviceTier(ChatCompletionChunk.ServiceTier.AUTO)
                .systemFingerprint("system_fingerprint")
                .usage(
                    CompletionUsage.builder()
                        .completionTokens(0L)
                        .promptTokens(0L)
                        .totalTokens(0L)
                        .completionTokensDetails(
                            CompletionTokensDetails.builder()
                                .acceptedPredictionTokens(0L)
                                .audioTokens(0L)
                                .reasoningTokens(0L)
                                .rejectedPredictionTokens(0L)
                                .build()
                        )
                        .promptTokensDetails(
                            PromptTokensDetails.builder().audioTokens(0L).cachedTokens(0L).build()
                        )
                        .build()
                )
                .build()

        val roundtrippedChatCompletionChunk =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(chatCompletionChunk),
                jacksonTypeRef<ChatCompletionChunk>(),
            )

        assertThat(roundtrippedChatCompletionChunk).isEqualTo(chatCompletionChunk)
    }
}
