// File generated from our OpenAPI spec by Stainless.

package com.dedalus_sdk.api.models.chat.completions

import com.dedalus_sdk.api.core.JsonValue
import com.dedalus_sdk.api.core.jsonMapper
import com.dedalus_sdk.api.models.JsonObjectInput
import com.dedalus_sdk.api.models.McpToolResult
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ChatCompletionTest {

    @Test
    fun create() {
        val chatCompletion =
            ChatCompletion.builder()
                .id("chatcmpl-123")
                .addChoice(
                    Choice.builder()
                        .index(0L)
                        .message(
                            ChatCompletionMessage.builder()
                                .content("The next Warriors game is tomorrow at 7:30 PM.")
                                .refusal("refusal")
                                .addAnnotation(
                                    ChatCompletionMessage.Annotation.builder()
                                        .urlCitation(
                                            ChatCompletionMessage.Annotation.UrlCitation.builder()
                                                .endIndex(0L)
                                                .startIndex(0L)
                                                .title("title")
                                                .url("url")
                                                .build()
                                        )
                                        .build()
                                )
                                .audio(
                                    ChatCompletionMessage.Audio.builder()
                                        .id("id")
                                        .data("data")
                                        .expiresAt(0L)
                                        .transcript("transcript")
                                        .build()
                                )
                                .functionCall(
                                    ChatCompletionMessage.FunctionCall.builder()
                                        .arguments("arguments")
                                        .name("name")
                                        .build()
                                )
                                .addToolCall(
                                    ChatCompletionMessageToolCall.builder()
                                        .id("id")
                                        .function(
                                            ChatCompletionMessageToolCall.Function.builder()
                                                .arguments("arguments")
                                                .name("name")
                                                .build()
                                        )
                                        .thoughtSignature("thought_signature")
                                        .build()
                                )
                                .build()
                        )
                        .finishReason(Choice.FinishReason.STOP)
                        .logprobs(
                            ChoiceLogprobs.builder()
                                .addContent(
                                    ChatCompletionTokenLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionTokenLogprob.TopLogprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .addRefusal(
                                    ChatCompletionTokenLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionTokenLogprob.TopLogprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .created(1677652288L)
                .model("gpt-4o-mini")
                .correlationId("correlation_id")
                .addDeferred(
                    DeferredCallResponse.builder()
                        .id("id")
                        .name("name")
                        .arguments(
                            JsonObjectInput.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .addBlockedBy("string")
                        .addDependency("string")
                        .venue("venue")
                        .build()
                )
                .mcpServerErrors(
                    ChatCompletion.McpServerErrors.builder()
                        .putAdditionalProperty(
                            "foo",
                            JsonValue.from(
                                mapOf(
                                    "message" to "message",
                                    "code" to "code",
                                    "recommendation" to "recommendation",
                                )
                            ),
                        )
                        .build()
                )
                .addMcpToolResult(
                    McpToolResult.builder()
                        .arguments(
                            JsonObjectInput.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .isError(true)
                        .serverName("server_name")
                        .toolName("tool_name")
                        .durationMs(0L)
                        .result("string")
                        .build()
                )
                .addPendingTool(
                    ChatCompletion.PendingTool.builder()
                        .id("id")
                        .arguments(
                            JsonObjectInput.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .addDependency("string")
                        .build()
                )
                .serverResults(
                    ChatCompletion.ServerResults.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .serviceTier(ChatCompletion.ServiceTier.AUTO)
                .systemFingerprint("system_fingerprint")
                .addToolsExecuted("search_events")
                .addToolsExecuted("get_event_details")
                .turnsConsumed(0L)
                .usage(
                    CompletionUsage.builder()
                        .completionTokens(12L)
                        .promptTokens(9L)
                        .totalTokens(21L)
                        .completionTokensDetails(
                            CompletionTokensDetails.builder()
                                .acceptedPredictionTokens(0L)
                                .audioTokens(0L)
                                .reasoningTokens(0L)
                                .rejectedPredictionTokens(0L)
                                .build()
                        )
                        .promptTokensDetails(
                            PromptTokensDetails.builder().audioTokens(0L).cachedTokens(0L).build()
                        )
                        .build()
                )
                .build()

        assertThat(chatCompletion.id()).isEqualTo("chatcmpl-123")
        assertThat(chatCompletion.choices())
            .containsExactly(
                Choice.builder()
                    .index(0L)
                    .message(
                        ChatCompletionMessage.builder()
                            .content("The next Warriors game is tomorrow at 7:30 PM.")
                            .refusal("refusal")
                            .addAnnotation(
                                ChatCompletionMessage.Annotation.builder()
                                    .urlCitation(
                                        ChatCompletionMessage.Annotation.UrlCitation.builder()
                                            .endIndex(0L)
                                            .startIndex(0L)
                                            .title("title")
                                            .url("url")
                                            .build()
                                    )
                                    .build()
                            )
                            .audio(
                                ChatCompletionMessage.Audio.builder()
                                    .id("id")
                                    .data("data")
                                    .expiresAt(0L)
                                    .transcript("transcript")
                                    .build()
                            )
                            .functionCall(
                                ChatCompletionMessage.FunctionCall.builder()
                                    .arguments("arguments")
                                    .name("name")
                                    .build()
                            )
                            .addToolCall(
                                ChatCompletionMessageToolCall.builder()
                                    .id("id")
                                    .function(
                                        ChatCompletionMessageToolCall.Function.builder()
                                            .arguments("arguments")
                                            .name("name")
                                            .build()
                                    )
                                    .thoughtSignature("thought_signature")
                                    .build()
                            )
                            .build()
                    )
                    .finishReason(Choice.FinishReason.STOP)
                    .logprobs(
                        ChoiceLogprobs.builder()
                            .addContent(
                                ChatCompletionTokenLogprob.builder()
                                    .token("token")
                                    .addByte(0L)
                                    .logprob(0.0)
                                    .addTopLogprob(
                                        ChatCompletionTokenLogprob.TopLogprob.builder()
                                            .token("token")
                                            .addByte(0L)
                                            .logprob(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .addRefusal(
                                ChatCompletionTokenLogprob.builder()
                                    .token("token")
                                    .addByte(0L)
                                    .logprob(0.0)
                                    .addTopLogprob(
                                        ChatCompletionTokenLogprob.TopLogprob.builder()
                                            .token("token")
                                            .addByte(0L)
                                            .logprob(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(chatCompletion.created()).isEqualTo(1677652288L)
        assertThat(chatCompletion.model()).isEqualTo("gpt-4o-mini")
        assertThat(chatCompletion.correlationId()).isEqualTo("correlation_id")
        assertThat(chatCompletion.deferred())
            .containsExactly(
                DeferredCallResponse.builder()
                    .id("id")
                    .name("name")
                    .arguments(
                        JsonObjectInput.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .addBlockedBy("string")
                    .addDependency("string")
                    .venue("venue")
                    .build()
            )
        assertThat(chatCompletion.mcpServerErrors())
            .isEqualTo(
                ChatCompletion.McpServerErrors.builder()
                    .putAdditionalProperty(
                        "foo",
                        JsonValue.from(
                            mapOf(
                                "message" to "message",
                                "code" to "code",
                                "recommendation" to "recommendation",
                            )
                        ),
                    )
                    .build()
            )
        assertThat(chatCompletion.mcpToolResults())
            .containsExactly(
                McpToolResult.builder()
                    .arguments(
                        JsonObjectInput.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .isError(true)
                    .serverName("server_name")
                    .toolName("tool_name")
                    .durationMs(0L)
                    .result("string")
                    .build()
            )
        assertThat(chatCompletion.pendingTools())
            .containsExactly(
                ChatCompletion.PendingTool.builder()
                    .id("id")
                    .arguments(
                        JsonObjectInput.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .name("name")
                    .addDependency("string")
                    .build()
            )
        assertThat(chatCompletion.serverResults())
            .isEqualTo(
                ChatCompletion.ServerResults.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(chatCompletion.serviceTier()).isEqualTo(ChatCompletion.ServiceTier.AUTO)
        assertThat(chatCompletion.systemFingerprint()).isEqualTo("system_fingerprint")
        assertThat(chatCompletion.toolsExecuted())
            .containsExactly("search_events", "get_event_details")
        assertThat(chatCompletion.turnsConsumed()).isEqualTo(0L)
        assertThat(chatCompletion.usage())
            .isEqualTo(
                CompletionUsage.builder()
                    .completionTokens(12L)
                    .promptTokens(9L)
                    .totalTokens(21L)
                    .completionTokensDetails(
                        CompletionTokensDetails.builder()
                            .acceptedPredictionTokens(0L)
                            .audioTokens(0L)
                            .reasoningTokens(0L)
                            .rejectedPredictionTokens(0L)
                            .build()
                    )
                    .promptTokensDetails(
                        PromptTokensDetails.builder().audioTokens(0L).cachedTokens(0L).build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val chatCompletion =
            ChatCompletion.builder()
                .id("chatcmpl-123")
                .addChoice(
                    Choice.builder()
                        .index(0L)
                        .message(
                            ChatCompletionMessage.builder()
                                .content("The next Warriors game is tomorrow at 7:30 PM.")
                                .refusal("refusal")
                                .addAnnotation(
                                    ChatCompletionMessage.Annotation.builder()
                                        .urlCitation(
                                            ChatCompletionMessage.Annotation.UrlCitation.builder()
                                                .endIndex(0L)
                                                .startIndex(0L)
                                                .title("title")
                                                .url("url")
                                                .build()
                                        )
                                        .build()
                                )
                                .audio(
                                    ChatCompletionMessage.Audio.builder()
                                        .id("id")
                                        .data("data")
                                        .expiresAt(0L)
                                        .transcript("transcript")
                                        .build()
                                )
                                .functionCall(
                                    ChatCompletionMessage.FunctionCall.builder()
                                        .arguments("arguments")
                                        .name("name")
                                        .build()
                                )
                                .addToolCall(
                                    ChatCompletionMessageToolCall.builder()
                                        .id("id")
                                        .function(
                                            ChatCompletionMessageToolCall.Function.builder()
                                                .arguments("arguments")
                                                .name("name")
                                                .build()
                                        )
                                        .thoughtSignature("thought_signature")
                                        .build()
                                )
                                .build()
                        )
                        .finishReason(Choice.FinishReason.STOP)
                        .logprobs(
                            ChoiceLogprobs.builder()
                                .addContent(
                                    ChatCompletionTokenLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionTokenLogprob.TopLogprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .addRefusal(
                                    ChatCompletionTokenLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .addTopLogprob(
                                            ChatCompletionTokenLogprob.TopLogprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .created(1677652288L)
                .model("gpt-4o-mini")
                .correlationId("correlation_id")
                .addDeferred(
                    DeferredCallResponse.builder()
                        .id("id")
                        .name("name")
                        .arguments(
                            JsonObjectInput.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .addBlockedBy("string")
                        .addDependency("string")
                        .venue("venue")
                        .build()
                )
                .mcpServerErrors(
                    ChatCompletion.McpServerErrors.builder()
                        .putAdditionalProperty(
                            "foo",
                            JsonValue.from(
                                mapOf(
                                    "message" to "message",
                                    "code" to "code",
                                    "recommendation" to "recommendation",
                                )
                            ),
                        )
                        .build()
                )
                .addMcpToolResult(
                    McpToolResult.builder()
                        .arguments(
                            JsonObjectInput.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .isError(true)
                        .serverName("server_name")
                        .toolName("tool_name")
                        .durationMs(0L)
                        .result("string")
                        .build()
                )
                .addPendingTool(
                    ChatCompletion.PendingTool.builder()
                        .id("id")
                        .arguments(
                            JsonObjectInput.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .addDependency("string")
                        .build()
                )
                .serverResults(
                    ChatCompletion.ServerResults.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .serviceTier(ChatCompletion.ServiceTier.AUTO)
                .systemFingerprint("system_fingerprint")
                .addToolsExecuted("search_events")
                .addToolsExecuted("get_event_details")
                .turnsConsumed(0L)
                .usage(
                    CompletionUsage.builder()
                        .completionTokens(12L)
                        .promptTokens(9L)
                        .totalTokens(21L)
                        .completionTokensDetails(
                            CompletionTokensDetails.builder()
                                .acceptedPredictionTokens(0L)
                                .audioTokens(0L)
                                .reasoningTokens(0L)
                                .rejectedPredictionTokens(0L)
                                .build()
                        )
                        .promptTokensDetails(
                            PromptTokensDetails.builder().audioTokens(0L).cachedTokens(0L).build()
                        )
                        .build()
                )
                .build()

        val roundtrippedChatCompletion =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(chatCompletion),
                jacksonTypeRef<ChatCompletion>(),
            )

        assertThat(roundtrippedChatCompletion).isEqualTo(chatCompletion)
    }
}
