// File generated from our OpenAPI spec by Stainless.

package com.dedalus_sdk.api.models.chat.completions

import com.dedalus_sdk.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ChoiceTest {

    @Test
    fun create() {
        val choice =
            Choice.builder()
                .index(0L)
                .message(
                    ChatCompletionMessage.builder()
                        .content("content")
                        .refusal("refusal")
                        .addAnnotation(
                            ChatCompletionMessage.Annotation.builder()
                                .urlCitation(
                                    ChatCompletionMessage.Annotation.UrlCitation.builder()
                                        .endIndex(0L)
                                        .startIndex(0L)
                                        .title("title")
                                        .url("url")
                                        .build()
                                )
                                .build()
                        )
                        .audio(
                            ChatCompletionMessage.Audio.builder()
                                .id("id")
                                .data("data")
                                .expiresAt(0L)
                                .transcript("transcript")
                                .build()
                        )
                        .functionCall(
                            ChatCompletionMessage.FunctionCall.builder()
                                .arguments("arguments")
                                .name("name")
                                .build()
                        )
                        .addToolCall(
                            ChatCompletionMessageToolCall.builder()
                                .id("id")
                                .function(
                                    ChatCompletionMessageToolCall.Function.builder()
                                        .arguments("arguments")
                                        .name("name")
                                        .build()
                                )
                                .thoughtSignature("thought_signature")
                                .build()
                        )
                        .build()
                )
                .finishReason(Choice.FinishReason.STOP)
                .logprobs(
                    ChoiceLogprobs.builder()
                        .addContent(
                            ChatCompletionTokenLogprob.builder()
                                .token("token")
                                .addByte(0L)
                                .logprob(0.0)
                                .addTopLogprob(
                                    ChatCompletionTokenLogprob.TopLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .addRefusal(
                            ChatCompletionTokenLogprob.builder()
                                .token("token")
                                .addByte(0L)
                                .logprob(0.0)
                                .addTopLogprob(
                                    ChatCompletionTokenLogprob.TopLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(choice.index()).isEqualTo(0L)
        assertThat(choice.message())
            .isEqualTo(
                ChatCompletionMessage.builder()
                    .content("content")
                    .refusal("refusal")
                    .addAnnotation(
                        ChatCompletionMessage.Annotation.builder()
                            .urlCitation(
                                ChatCompletionMessage.Annotation.UrlCitation.builder()
                                    .endIndex(0L)
                                    .startIndex(0L)
                                    .title("title")
                                    .url("url")
                                    .build()
                            )
                            .build()
                    )
                    .audio(
                        ChatCompletionMessage.Audio.builder()
                            .id("id")
                            .data("data")
                            .expiresAt(0L)
                            .transcript("transcript")
                            .build()
                    )
                    .functionCall(
                        ChatCompletionMessage.FunctionCall.builder()
                            .arguments("arguments")
                            .name("name")
                            .build()
                    )
                    .addToolCall(
                        ChatCompletionMessageToolCall.builder()
                            .id("id")
                            .function(
                                ChatCompletionMessageToolCall.Function.builder()
                                    .arguments("arguments")
                                    .name("name")
                                    .build()
                            )
                            .thoughtSignature("thought_signature")
                            .build()
                    )
                    .build()
            )
        assertThat(choice.finishReason()).isEqualTo(Choice.FinishReason.STOP)
        assertThat(choice.logprobs())
            .isEqualTo(
                ChoiceLogprobs.builder()
                    .addContent(
                        ChatCompletionTokenLogprob.builder()
                            .token("token")
                            .addByte(0L)
                            .logprob(0.0)
                            .addTopLogprob(
                                ChatCompletionTokenLogprob.TopLogprob.builder()
                                    .token("token")
                                    .addByte(0L)
                                    .logprob(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .addRefusal(
                        ChatCompletionTokenLogprob.builder()
                            .token("token")
                            .addByte(0L)
                            .logprob(0.0)
                            .addTopLogprob(
                                ChatCompletionTokenLogprob.TopLogprob.builder()
                                    .token("token")
                                    .addByte(0L)
                                    .logprob(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val choice =
            Choice.builder()
                .index(0L)
                .message(
                    ChatCompletionMessage.builder()
                        .content("content")
                        .refusal("refusal")
                        .addAnnotation(
                            ChatCompletionMessage.Annotation.builder()
                                .urlCitation(
                                    ChatCompletionMessage.Annotation.UrlCitation.builder()
                                        .endIndex(0L)
                                        .startIndex(0L)
                                        .title("title")
                                        .url("url")
                                        .build()
                                )
                                .build()
                        )
                        .audio(
                            ChatCompletionMessage.Audio.builder()
                                .id("id")
                                .data("data")
                                .expiresAt(0L)
                                .transcript("transcript")
                                .build()
                        )
                        .functionCall(
                            ChatCompletionMessage.FunctionCall.builder()
                                .arguments("arguments")
                                .name("name")
                                .build()
                        )
                        .addToolCall(
                            ChatCompletionMessageToolCall.builder()
                                .id("id")
                                .function(
                                    ChatCompletionMessageToolCall.Function.builder()
                                        .arguments("arguments")
                                        .name("name")
                                        .build()
                                )
                                .thoughtSignature("thought_signature")
                                .build()
                        )
                        .build()
                )
                .finishReason(Choice.FinishReason.STOP)
                .logprobs(
                    ChoiceLogprobs.builder()
                        .addContent(
                            ChatCompletionTokenLogprob.builder()
                                .token("token")
                                .addByte(0L)
                                .logprob(0.0)
                                .addTopLogprob(
                                    ChatCompletionTokenLogprob.TopLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .addRefusal(
                            ChatCompletionTokenLogprob.builder()
                                .token("token")
                                .addByte(0L)
                                .logprob(0.0)
                                .addTopLogprob(
                                    ChatCompletionTokenLogprob.TopLogprob.builder()
                                        .token("token")
                                        .addByte(0L)
                                        .logprob(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedChoice =
            jsonMapper.readValue(jsonMapper.writeValueAsString(choice), jacksonTypeRef<Choice>())

        assertThat(roundtrippedChoice).isEqualTo(choice)
    }
}
